### PR TITLE
adding maintainers file

### PR DESCRIPTION
**Pull request by leec94**
Changes 
- added maintainers file
- resolves issue https://github.com/open-horizon-services/service-edgex-foundry/issues/1

Signed-off-by: leec94 <leec94@bu.edu>

### CODE REVIEW

**Review by johnwalicki — APPROVED** [review]
Approved

**Comment by johnwalicki** [comment]
@leec94  - Thanks for contributing to Open Horizon !

**Comment by johnwalicki** [comment]
Fixes #1

**Comment by joewxboy** [comment]
Congratulations, @leec94 looks like you're officially a project Contributor now.  Let me know if you'd like to get on a call to learn some more about the structure of the project, where we're going, and the different opportunities we have for eminence.

**Pull request merged**
